name: Django CI/CD

on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  test-lint:
    name: Run Migrations, Tests & Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker containers
        run: docker compose build

      - name: Run Migration
        run: docker compose run --rm app sh -c "python manage.py migrate --noinput"

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test --verbosity=2"

      - name: Lint Code
        run: docker compose run --rm app sh -c "flake8"
